library TourCmnl;

uses
  SysUtils,
  Classes,
  ComnUtil in 'ComnUtil.pas',
  AzMsgDlg in 'AzMsgDlg.pas',
  LibConsts in 'LibConsts.pas',
  ShelUtil in 'ShelUtil.pas',
  TimeSelDlg in 'TimeSelDlg.pas' {TimeSelectDlg},
  JpgFrmtDlg in 'JpgFrmtDlg.pas' {JpegImageFormatDlg},
  RegExpr in 'RegExpr.pas';

{$R *.RES}

exports
  IntDivision,
  SumDateAndTime,
  DateAddMonth,
  DateAddYear,
  TimeAddSecond,
  TimeAddMinute,
  TimeAddHour,   
  YearAge,
  YearAgeByDate,
  DurationToTime,
  GetInitialReportPeriod,
  SelectDateFromPicker,
  SelectTimeFromPicker,
  ExecuteJpegImageFormatDlg,
  JpegSizedCopyCreate,
  AzCountString,
  AzDayCountString,
  AzNightCountString,
  AzMonthCountString,
  AzYearCountString,
  AzChooseCaptionString,
  AzConfirmDlg,
  AzConfirmDlgYC,
  AzConfirmDlgYN,
  AzConfirmFmtDlg,
  AzConfirmFmtDlgYC,
  AzConfirmFmtDlgYN,
  AzErrorDlg,
  AzErrorFmtDlg,
  AzErrorHlpDlg,
  AzErrorFmtHlpDlg,
  AzInformFmtDlg,
  AzInformDlg,
  AzWarningDlg,
  AzWarningDlgYC,
  AzWarningDlgYN,
  AzWarningFmtDlg,
  AzWarningFmtDlgYC,
  AzWarningFmtDlgYN,
  AzInputDlg,
  AzInputQuery,
  AzSplashPromptForm,
  AzShellOutward,
  AzShellUtil,
  AzEMailSend,
  AzWebBrowse,
  AzCheckEmailAddress,
  AzCheckHttpAddress,
  AzCheckFtpAddress,
  AzCheckRegularExpression;

begin
end.
