select CITY_ADM_UNIT_INFO.*, CITY_ADM_UNIT_TYPE_INFO.NAME from CITY_ADM_UNIT_INFO
left join CITY_ADM_UNIT_TYPE_INFO on CITY_ADM_UNIT_TYPE_INFO.id = CITY_ADM_UNIT_INFO.id_city_adm_unit_type_info
where ID_CITY_ADM_UNIT = :ID
