 select COMPANIES_PARAM_NAME.*, COMPANIES_PARAM_KIND.name KINDNAME, COMPANIES_PARAM_KIND.aorder from COMPANIES_PARAM_NAME
 left join COMPANIES_PARAM_KIND on COMPANIES_PARAM_NAME.atype = companies_param_KIND.id where COMPANIES_PARAM_NAME.atype >=0
